//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyStatusRequest
    {
        public int ID { get; set; }
        public string ProductNo { get; set; }
        public string ProposalNo { get; set; }
        public string RenewalNo { get; set; }
        public string EndorsNo { get; set; }
        public string Response { get; set; }
    }
}
